version: '3.9'

services:
  postgres:
    build: ./db_setup
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=pguser
      - POSTGRES_MULTIPLE_DBS=contacts_db,keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=pguser
      - DB_SCHEMA=public
      - DB_PASSWORD=secret
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: [ "start-dev" ]